### ISSUE TITLE
Occassional 'Bad Request' Errors

### ISSUE THREAD

**Issue by irico1997** [gcflames5/ynab-splitwise-integration#14]
About 1/10th of my transactions added give "Bad Request" errors. I'm not sure about the commonality between them, here are a few examples:

[don't remember run time]
```
New transaction found: Expense: [desc: lyfts for concert, cost: 32.730000, date: Wed May 03 17:10:03 PDT 2023]
Uploading new expense to YNAB: Expense: [desc: lyfts for concert, sw_uuid:-1956133770, cost: 32.730000, date: Wed May 03 17:10:03 PDT 2023]
ynab.client.invoker.ApiException: Bad Request
	at ynab.client.invoker.ApiClient.handleResponse(ApiClient.java:926)
	at ynab.client.invoker.ApiClient.execute(ApiClient.java:842)
	at ynab.client.api.TransactionsApi.createTransactionWithHttpInfo(TransactionsApi.java:291)
	at ynab.client.api.TransactionsApi.createTransaction(TransactionsApi.java:276)
	at com.github.gclfames5.ynab.YNABHandler.addTransaction(YNABHandler.java:91)
	at com.github.gclfames5.Main.main(Main.java:106)
```
[run on 5/14, 1:21am central european time]
```
Uploading new & updated expense to YNAB: Expense: [desc: florence din tip, cost: 16.950000, date: Wed May 10 11:33:41 CEST 2023]
ynab.client.invoker.ApiException: Bad Request
	at ynab.client.invoker.ApiClient.handleResponse(ApiClient.java:926)
	at ynab.client.invoker.ApiClient.execute(ApiClient.java:842)
	at ynab.client.api.TransactionsApi.createTransactionWithHttpInfo(TransactionsApi.java:291)
	at ynab.client.api.TransactionsApi.createTransaction(TransactionsApi.java:276)
	at com.github.gclfames5.ynab.YNABHandler.addTransaction(YNABHandler.java:91)
	at com.github.gclfames5.Main.main(Main.java:161)
```
```
New transaction found: Expense: [desc: xfinity :-(, cost: 64.730000, date: Sat May 13 15:48:43 CEST 2023]
Uploading new expense to YNAB: Expense: [desc: xfinity :-(, sw_uuid:-1936353136, cost: 64.730000, date: Sat May 13 15:48:43 CEST 2023]
ynab.client.invoker.ApiException: Bad Request
	at ynab.client.invoker.ApiClient.handleResponse(ApiClient.java:926)
	at ynab.client.invoker.ApiClient.execute(ApiClient.java:842)
	at ynab.client.api.TransactionsApi.createTransactionWithHttpInfo(TransactionsApi.java:291)
	at ynab.client.api.TransactionsApi.createTransaction(TransactionsApi.java:276)
	at com.github.gclfames5.ynab.YNABHandler.addTransaction(YNABHandler.java:91)
	at com.github.gclfames5.Main.main(Main.java:106)
```
[run 6/5, 2:19pm PST]
```
New transaction found: Expense: [desc: costco, cost: 112.110000, date: Mon Jun 05 00:02:58 PDT 2023]
Uploading new expense to YNAB: Expense: [desc: costco, sw_uuid:-1888666960, cost: 112.110000, date: Mon Jun 05 00:02:58 PDT 2023]
ynab.client.invoker.ApiException: Bad Request
	at ynab.client.invoker.ApiClient.handleResponse(ApiClient.java:926)
	at ynab.client.invoker.ApiClient.execute(ApiClient.java:842)
	at ynab.client.api.TransactionsApi.createTransactionWithHttpInfo(TransactionsApi.java:291)
	at ynab.client.api.TransactionsApi.createTransaction(TransactionsApi.java:276)
	at com.github.gclfames5.ynab.YNABHandler.addTransaction(YNABHandler.java:91)
	at com.github.gclfames5.Main.main(Main.java:106)
```

**Comment by irico1997** [comment]
Additional info: For the 6/5 run, the expense mentioned was added on June 4th PDT. I don't know how much this matters because it seems like all of my expense times are off by 7 hours.

**Comment by irico1997** [comment]
I'm not very good with github and I'm not sure how to contribute directly. But I have https://github.com/irico1997/ynab-splitwise-integration/pull/1 on my fork for fixing this issue if you want to update it here as well.
