### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by VanillaChief** [gcflames5/ynab-splitwise-integration#8]
I followed the step-by-step manual in the wiki.

When I try to run `java -jar ynab-splitwise.jar` I get following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/github/gclfames5/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

`java -version`gives me following:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```
(I am on macOS 10.14.6 if that's relevant)

Do I have the wrong Java version? Or did I do something wrong in the setup?

Thanks for your time and help in advance!

**Comment by VanillaChief** [comment]
Found my mistake: Had an old version of the Java SE Development Kit installed. Once I downloaded the correct version it worked. I guess this is a rookie mistake, but posting it anyways for future rookies to see.
